FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

# Use built-in node user in alpine
RUN chown -R node:node /app
USER node

CMD ["npm", "run", "dev"]
